# Generated by Django 3.0.3 on 2020-03-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('berth_preference', models.CharField(choices=[('Upper', 'Upper'), ('Lower', 'Lower'), ('Middel', 'Middel'), ('Side', 'Side')], max_length=10)),
                ('coach', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4')], max_length=10)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('RAC ', 'RAC'), ('Waiting', 'Waiting')], max_length=10)),
            ],
        ),
    ]
